name = "sub"
main = "sub-converter-worker/build/worker/shim.mjs"
compatibility_date = "2025-10-12"

[build]
command = "cargo install -q worker-build && cd sub-converter-worker && worker-build --release"

# Environment variables (set via Cloudflare Dashboard or wrangler CLI):
# - PROFILE_TOKEN: Token for /profile endpoint authentication
# - TEMPLATE_TOKEN: Token for template upload authentication

[[r2_buckets]]
binding = 'TEMPLATE'
bucket_name = 'template'
preview_bucket_name = 'template-dev'
