name = "sub"
main = "sub-converter-worker/build/worker/shim.mjs"
compatibility_date = "2025-10-12"

[build]
command = "cargo install -q worker-build && cd sub-converter-worker && worker-build --release"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[[r2_buckets]]
binding = 'TEMPLATE'
bucket_name = 'template'
preview_bucket_name = 'template-dev'

[[kv_namespaces]]
binding = 'RULES'
id = '4a5e0f3e4e5c423da540b17958bdad36'
preview_id = '10f060cbb4c24c61963c48d28626cc9b'
