name = "sub"
main = "sub-converter-worker/build/worker/shim.mjs"
compatibility_date = "2025-10-12"

[build]
command = "cargo install -q worker-build && cd sub-converter-worker && worker-build --release"
